[build]
  publish = "public"
  command = "gatsby develop"
[build.environment]
  YARN_VERSION = "1.21.1"
[[redirects]]
  from = "/docs"
  to = "/docs/getting-started/setup"
  status = 200
  force = true